sudo: false
language: android
android:
  components:
   - tools
   - platform-tools
   - tools
   - build-tools-26.0.1
   - android-26
   - extra-google-google_play_services
   - extra-google-m2repository
   - extra-android-m2repository
   - sys-img-armeabi-v7a-google_apis-22
   - sys-img-armeabi-v7a-google_apis-26
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a --tag google_apis
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
notifications:
  email: false
