sudo: false
language: android
android:
  components:
  - tools
  - android-26
  - platform-tools
  - build-tools-26.0.2
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-26
licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
